import { Montserrat } from 'next/font/google';
import "./globals.css";
import Navbar from "./Componet/MainLayout/Navber";
import Footer from "./Componet/MainLayout/Footer/Footer";

const montserrat = Montserrat({
  subsets: ['latin'], // Optimize for Latin characters
  weight: ['400', '700'], // Specify weights (e.g., regular and bold)
  style: ['normal', 'italic'], // Optional: include italic style
  variable: '--font-montserrat', // Optional: for CSS variable usage
});

export const metadata = {
  title: "MANS Packaging",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  className={montserrat.className}
      >
        <Navbar/>
        {children}
        <Footer/> 
      </body>
    </html>
  );
}
